modLoader="javafml"
loaderVersion="[35,)"
license="Not specified"

[[mods]]
modId="infinitepowerupd"
version="1.0.0ur"
displayName="The Crimson"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/MicherGit/CrimsonMod"
logoFile="logo.png"
authors="Zetabloox"
description='''
Crimsontale mod for Minecraft 1.16.4
'''

[[dependencies.infinitepowerupd]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




